version: "3.7"

services:
    selfweb:
        image: ninguna
        container_name: selfweb
        restart: unless-stopped
        volumes:
            - selfweb_log:/var/log/selfweb
            - selfweb_config:/config
        networks:
            - selfweb_network
        environment:
            SPRING_CONFIG_LOCATION: /config/application.properties            
            TZ: Europe/Madrid
                                                    
    nginx:
        image: nginx:1.23.1
        container_name: nginx
        depends_on:
            - selfweb
        ports:
            - 443:443
        restart: unless-stopped
        volumes:
            - nginx_config:/etc/nginx
            - nginx_data:/var/www/html
            - nginx_log:/var/log/nginx
        networks:
            - selfweb_network
            
    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        ports:
            - 9000:9000
        restart: unless-stopped
        volumes:
            - portainer_data:/data
            - /var/run/docker.sock:/var/run/docker.sock
        
volumes:
    selfweb_log:
        external: true
    selfweb_config:
        external: true
    nginx_config:
        external: true
    nginx_data:
        external: true
    nginx_log:
        external: true
    portainer_data:
        external: true

networks:
    selfweb_network:
        name: selfweb_network
        external: true

