#########################################################################################################
# Pipeline simple para manejar proyectos maven/java. Los diferentes jobs estan descritos en archivos
# del directorio jobs/maven.
# Este pipeline se ejecuta solo en caso de push de cualquier rama, aunque buena parte de los
# jobs se ejecutan solo para las ramas master o develop. 
#
# Vers  Por Fecha      Notas
# ----- --- ---------- ----------------------------------------------------------------------------------
# 1.0.0 FNG 26/07/2022 Version inicial
#
#########################################################################################################
variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"
  # Como acceder a gitlab desde un executor
  ORIGIN_URL: "https://oauth2:${CICD_TOKEN}@${CICD_HOST}/${CI_PROJECT_PATH}.git"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'    # Solo en caso de push

# Esta es una imagen propia, con maven y git, y uso local. Requiere cambiar pull_policy en config.toml a 'if-not-present'
image: ck-maven-executor:1.0.0 

cache:
  # Definimos la clave como el nombre del branch en el que hacemos push, de este modo
  # separamos la informacion cacheada para cada rama, para no interferir en otros pipelines.
  key: "$CI_COMMIT_REF_NAME"

# Etapas posibles del pipeline
stages:
  - prepare
  - compile
  - test
  - sonar
  - build
  - register
  - docker
  - tag

# Includes
include: 
  - project: 'comunytek/cicd-librerias'
    ref: master
    file: 
      # compile-job: comprueba que no hay errores de compilacion
      - 'jobs/maven/compile-simple.yml'
      # sonar-job: verifica calidad del codigo
      - 'jobs/maven/sonar-simple.yml'
      # build-job: genera el fat-jar
      - 'jobs/maven/build-simple.yml'
      # register-job: Sube el artefacto al registry
      - 'jobs/maven/register-simple.yml'
      # docker-job: crea una imagen docker y la guarda en el registry de gitlab
      - 'jobs/maven/docker-simple.yml'
      # tag-job: Genera tag (solo rama master) (manual)
      - 'jobs/maven/tag-simple.yml'

