VM_NAME = "test-cicd-prod"
HYPERV_HOST = "192.168.1.29"
HYPERV_NSW_NAME = "FngSwitch"
HYPERV_VHD_PATH = "C:\\HyperV\\Discos\\test-hyperv-prod.vhdx"
HYPERV_SEED_DISK = "C:\\HyperV\\Discos-semilla\\alpine-test.vhdx"