############################################################################
# Ejemplo de .gitlab-ci.yml. Debe estar en el root del proyecto a tratar.
# Usamos el pipeline simple para maven y springboot.
# El codigo en el proyecto "cicd-librerias" puede ser empleado
# por cualquier miembro del grupo "comunytek", pero sólo pueden
# editarlo los managers. El pipeline que usamos en este proyecto es:
#
#     /comunytek/cicd-librerias/pipelines/maven-springboot-simple.yml
#
############################################################################

variables:
  #
  # Si registramos, creamos docker y tag, etc. en SNAPSHOT podemos agregar (opcionalmente)
  # un numero de snapshot a la vesion del proyecto para identificar registros y tag.
  #
  SNAPSHOT_NUMBER: "002"
  #
  # Si estamos en una rama de hotfix, se ejecuta todo el pipeline,
  # aunque las etapas sonar y test admiten errores.
  # Comentar esta linea, o dejar en blanco el valor, una vez liberado el hotfix.
  # Opcionalmente, podemos indicar un numero de hotfix, para registro, docker y tag.
  # En la version del proyecto, se respeta la que se indica en el pom.xml. 
  #
  HOTFIX_BRANCH: ""
  HOTFIX_NUMBER: "002"

#
# Pipeline predefinido
#
include:
   project: 'comunytek/cicd-librerias'
   ref: master
   file: 'pipelines/maven-springboot-simple.yml'

############################# E O F ##############################

   